[tools]
go = "1.23.4"
golangci-lint = "1.62.2"
gofumpt = "0.7.0"
goreleaser = "2.5.0"

[env]
CGO_ENABLED = "0"
GOFLAGS = "-mod=readonly"

[tasks.install]
description = "Install project dependencies"
run = "go mod download && go mod tidy"

[tasks.build]
description = "Build the s3ry binary"
run = "go build -ldflags='-s -w -X main.version={{exec(git describe --tags --always)}} -X main.commit={{exec(git rev-parse HEAD)}} -X main.date={{exec(date -u +%Y-%m-%dT%H:%M:%SZ)}}' -o bin/s3ry ./cmd/s3ry"

[tasks.build-all]
description = "Build for all platforms"
run = """
mkdir -p dist
GOOS=darwin GOARCH=amd64 go build -ldflags='-s -w' -o dist/s3ry-darwin-amd64 ./cmd/s3ry
GOOS=darwin GOARCH=arm64 go build -ldflags='-s -w' -o dist/s3ry-darwin-arm64 ./cmd/s3ry
GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o dist/s3ry-linux-amd64 ./cmd/s3ry
GOOS=linux GOARCH=arm64 go build -ldflags='-s -w' -o dist/s3ry-linux-arm64 ./cmd/s3ry
GOOS=windows GOARCH=amd64 go build -ldflags='-s -w' -o dist/s3ry-windows-amd64.exe ./cmd/s3ry
"""

[tasks.dev]
description = "Run in development mode with hot reload"
run = "go run ./cmd/s3ry"

[tasks.test]
description = "Run all tests"
run = "go test -v -race -coverprofile=coverage.out ./..."

[tasks.test-integration]
description = "Run integration tests"
run = "go test -v -tags=integration ./test/integration/..."

[tasks.lint]
description = "Run linting"
run = "golangci-lint run --fix"

[tasks.fmt]
description = "Format code"
run = "gofumpt -l -w ."

[tasks.check]
description = "Run all checks (fmt, lint, test)"
depends = ["fmt", "lint", "test"]

[tasks.clean]
description = "Clean build artifacts"
run = "rm -rf bin/ dist/ coverage.out"

[tasks.release]
description = "Create a new release"
run = "goreleaser release --clean"

[tasks.release-snapshot]
description = "Create a snapshot release"
run = "goreleaser release --snapshot --clean"

[tasks.setup]
description = "Setup development environment"
run = """
echo "🚀 Setting up s3ry development environment..."
mise install
go mod download
mkdir -p bin dist
echo "✅ Development environment ready!"
"""